name: forge2d_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.4.0
  flame: ^1.33.0
  flame_forge2d: ^0.19.2+1
  flame_kenney_xml: ^0.1.1+17
  xml: ^6.6.1
  equatable: ^2.0.7
  vibration: ^3.1.4
  go_router: ^17.0.0
  supabase_flutter: ^2.10.3
  google_fonts: ^6.3.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono.jpeg"
  min_sdk_android: 21 # set to min_sdk_version of your Android app

flutter_native_splash:
  color: "#FFFFFF" # You can change this to match your app's primary color
  image: "assets/images/splash.jpeg"
  android_12:
    image: "assets/images/splash.jpeg"
    color: "#FFFFFF"
  web: false # Set to true if you want to generate for web
  ios_content_mode: "scaleAspectFill" # or "center"
  android_gravity: "center" # or "fill"
  fullscreen: true # Set to false if you want to show status bar

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/music/
